Name: Mona Mashta

Occupation

Introduction:

Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

Step 1. Import the necessary libraries

import pandas as pd

In [1]:
import pandas as pd


Step 2. Import the dataset from this address.

Step 3. Assign it to a variable called users.

In [2]:
url ="https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user "

In [6]:
users = pd.read_csv(url, sep="|")

In [7]:
users.head()

   user_id  age gender  occupation zip_code
0        1   24      M  technician    85711
1        2   53      F       other    94043
2        3   23      M      writer    32067
3        4   24      M  technician    43537
4        5   33      F       other    15213

Step 4. Discover what is the mean age per occupation

In [11]:
users.groupby('occupation')[['age']].mean()

                     age
occupation
administrator  38.746835
artist         31.392857
doctor         43.571429
educator       42.010526
engineer       36.388060
entertainment  29.222222
executive      38.718750
healthcare     41.562500
homemaker      32.571429
lawyer         36.750000
librarian      40.000000
marketing      37.615385
none           26.555556
other          34.523810
programmer     33.121212
retired        63.071429
salesman       35.666667
scientist      35.548387
student        22.081633
technician     33.148148
writer         36.311111