# Investor - Flow of Funds - US
Introduction:

Special thanks to: https://github.com/rgrp for sharing the dataset.

### Step 1. Import the necessary libraries

In [15]:
import pandas as pd

### Step 2. Import the dataset from this address.

### Step 3. Assign it to a variable called

In [16]:
flows = pd.read_csv('https://raw.githubusercontent.com/datasets/investor-flow-of-funds-us/master/data/weekly.csv')
flows.head()

,Date,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
0,2022-07-06,10167,NaN,3058,NaN,842,NaN,2216,NaN
1,2022-07-13,7409,NaN,2808,NaN,2067,NaN,741,NaN
2,2022-07-20,3468,NaN,102,NaN,-417,NaN,519,NaN
3,2022-07-27,14213,NaN,9667,NaN,8598,NaN,1069,NaN
4,2022-08-03,9786,NaN,4016,NaN,3079,NaN,937,NaN

### Step 4. What is the frequency of the dataset?

In [17]:
flows['Date'] = pd.to_datetime(flows['Date'])

flows = flows.set_index('Date')

print(flows.index.freq)

None

### Step 5. Set the column Date as the index.

In [18]:
flows

,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
Date,,,,,,,,
2022-07-06,10167,NaN,3058,NaN,842,NaN,2216,NaN
2022-07-13,7409,NaN,2808,NaN,2067,NaN,741,NaN
2022-07-20,3468,NaN,102,NaN,-417,NaN,519,NaN
2022-07-27,14213,NaN,9667,NaN,8598,NaN,1069,NaN
2022-08-03,9786,NaN,4016,NaN,3079,NaN,937,NaN
...,...,...,...,...,...,...,...,...
2026-02-25,62363,NaN,27334,NaN,8279,NaN,19054,NaN
2026-03-04,24299,NaN,12227,NaN,-652,NaN,12879,NaN
2026-03-11,22797,NaN,11869,NaN,4291,NaN,7578,NaN
2026-03-18,25057,NaN,12807,NaN,2823,NaN,9984,NaN
2026-03-25,40513,NaN,31891,NaN,29748,NaN,2143,NaN

### Step 6. What is the type of the index?

In [21]:
flows.index

DatetimeIndex(['2022-07-06', '2022-07-13', '2022-07-20', '2022-07-27',
               '2022-08-03', '2022-08-10', '2022-08-17', '2022-08-24',
               '2022-08-31', '2022-09-07',
               ...
               '2025-10-01', '2025-10-08', '2026-02-04', '2026-02-11',
               '2026-02-18', '2026-02-25', '2026-03-04', '2026-03-11',
               '2026-03-18', '2026-03-25'],
              dtype='datetime64[ns]', name='Date', length=118, freq=None)

### Step 7. Set the index to a DatetimeIndex type

In [25]:
import datetime
flows.index = pd.to_datetime(flows.index)
type(flows.index)

pandas.core.indexes.datetimes.DatetimeIndex

### Step 8. Change the frequency to monthly, sum the values and assign it to monthly.