Name: Mpna Mashtaa


Ex1 - Filtering and Sorting Data

This time we are going to pull data directly from the internet. Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

Step 1. Import the necessary libraries

In [43]:
import pandas as pd

Step 2. Import the dataset from this address.

Step 3. Assign it to a variable called chipo.

In [91]:
url= "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"

chipo = pd.read_csv(url,sep="\t")

Step 4. How many products cost more than $10.00?

In [92]:
chipo.head(1)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39

In [93]:

chipo["item_price"]= chipo.item_price.apply(lambda x: (float(x[1:-1])))
chipo.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98

In [94]:
over10= chipo[chipo["item_price"]>10.00]
print(over10['item_name'].nunique())

31

Step 5. What is the price of each item?


print a data frame with only three columns item_name choice_description and product_price

In [106]:
menu= chipo[['item_name','choice_description','item_price']].sort_values(by= 'item_price', ascending= False).drop_duplicates()
menu

,item_name,choice_description,item_price
3598,Chips and Fresh Tomato Salsa,NaN,44.25
3480,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",35.25
3602,Chicken Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",35.00
1254,Chicken Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",35.00
3601,Veggie Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",33.75
...,...,...,...
53,Canned Soda,[Sprite],1.09
28,Canned Soda,[Dr. Pepper],1.09
2538,Canned Soda,[Diet Dr. Pepper],1.09
3897,Canned Soda,[Mountain Dew],1.09
200,Canned Soda,[Diet Coke],1.09

Step 6. Sort by the name of the item

In [103]:
chipo.sort_values(by= 'item_name', ascending=False)

,order_id,quantity,item_name,choice_description,item_price
3889,1559,2,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",16.98
2851,1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49
738,304,1,Veggie Soft Tacos,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25
1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49
2384,948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75
...,...,...,...,...,...
1916,774,1,6 Pack Soft Drink,[Diet Coke],6.49
1124,465,1,6 Pack Soft Drink,[Coke],6.49
3789,1517,1,6 Pack Soft Drink,[Diet Coke],6.49
1392,566,1,6 Pack Soft Drink,[Diet Coke],6.49
3614,1448,1,6 Pack Soft Drink,[Nestea],6.49

Step 7. What was the quantity of the most expensive item ordered?

In [111]:
menu['item_name'].head(1)

3598    Chips and Fresh Tomato Salsa
Name: item_name, dtype: object

Step 8. How many times was a Veggie Salad Bowl ordered?

In [114]:
qua = chipo[chipo['item_name']=="Veggie Salad Bowl"]['quantity'].sum()
print(qua)

18

Step 9. How many times did someone order more than one Canned Soda?

In [125]:
sodas= ((chipo['item_name'] == "Canned Soda")& (chipo['quantity'] > 1)).sum()
print(sodas)

20